"""Meta-programming — agent writes programs that write programs.

The agent can:
  - Generate code generators
  - Create DSLs (Domain-Specific Languages)
  - Write AST transformers
  - Build code templates
  - Generate macros

This is the highest level of abstraction: programs that manipulate programs.
"""
from __future__ import annotations

import textwrap
from dataclasses import dataclass, field
from typing import Any


@dataclass
class Macro:
    """A code macro — expands to a larger code block."""
    name: str
    template: str  # template with {placeholders}
    parameters: list[str]  # parameter names
    description: str = ""


@dataclass
class GeneratedProgram:
    """A program generated by a meta-program."""
    code: str
    generator: str  # which generator produced it
    language: str = "python"
    metadata: dict[str, Any] = field(default_factory=dict)


class MetaProgrammer:
    """Writes programs that write programs."""

    # Built-in macros.
    BUILTIN_MACROS: list[Macro] = [
        Macro(
            name="create_endpoint",
            template='''@app.route("{path}", methods=["{method}"])
def {handler_name}():
    """{description}"""
    # TODO: implement handler
    return {{"status": "ok"}}
''',
            parameters=["path", "method", "handler_name", "description"],
            description="Generate a Flask/FastAPI endpoint",
        ),
        Macro(
            name="create_test",
            template='''def test_{function_name}():
    """Test for {function_name}."""
    # Arrange
    {arrange}
    # Act
    result = {function_name}({input})
    # Assert
    assert result == {expected}
''',
            parameters=["function_name", "arrange", "input", "expected"],
            description="Generate a unit test",
        ),
        Macro(
            name="create_class",
            template='''class {class_name}:
    """{description}"""

    def __init__(self{init_params}):
        {init_body}
        pass

    def __repr__(self):
        return f"{class_name}({{repr_args}})"
''',
            parameters=["class_name", "description", "init_params", "init_body", "repr_args"],
            description="Generate a Python class",
        ),
        Macro(
            name="create_dataclass",
            template='''@dataclass
class {class_name}:
    """{description}"""
    {fields}
''',
            parameters=["class_name", "description", "fields"],
            description="Generate a dataclass",
        ),
        Macro(
            name="create_cli",
            template='''import argparse

def {function_name}_cli():
    parser = argparse.ArgumentParser(description="{description}")
    {arguments}
    args = parser.parse_args()
    {handler}

if __name__ == "__main__":
    {function_name}_cli()
''',
            parameters=["function_name", "description", "arguments", "handler"],
            description="Generate a CLI entry point",
        ),
    ]

    def __init__(self) -> None:
        self.macros: dict[str, Macro] = {m.name: m for m in self.BUILTIN_MACROS}

    def expand_macro(self, macro_name: str, **kwargs: str) -> GeneratedProgram:
        """Expand a macro with the given parameters."""
        macro = self.macros.get(macro_name)
        if macro is None:
            return GeneratedProgram(code=f"# Unknown macro: {macro_name}", generator="error")
        try:
            code = macro.template.format(**kwargs)
            # Dedent for clean output.
            code = textwrap.dedent(code)
            return GeneratedProgram(code=code, generator=f"macro:{macro_name}", metadata={"macro": macro_name, "params": kwargs})
        except KeyError as exc:
            return GeneratedProgram(code=f"# Missing parameter: {exc}", generator="error")

    def add_macro(self, macro: Macro) -> None:
        self.macros[macro.name] = macro

    def list_macros(self) -> list[tuple[str, str]]:
        return [(m.name, m.description) for m in self.macros.values()]

    def generate_dsl(self, name: str, operations: list[tuple[str, str]]) -> GeneratedProgram:
        """Generate a simple DSL parser.

        ``operations`` is a list of (operation_name, description) pairs.
        """
        lines = [
            f'"""Generated DSL: {name}"""',
            "import re",
            "",
            f"class {name.title()}DSL:",
            f'    """A DSL for {name}."""',
            "",
            "    def __init__(self):",
            "        self.operations = {}",
        ]
        for op_name, op_desc in operations:
            lines.extend([
                "",
                f"    def {op_name}(self, *args):",
                f'        """{op_desc}"""',
                f'        self.operations["{op_name}"] = args',
                "        return self",
            ])
        lines.extend([
            "",
            "    def execute(self):",
            '        """Execute all operations."""',
            "        results = []",
            "        for op, args in self.operations.items():",
            "            results.append(f\"{op}({args})\")",
            "        return results",
        ])
        return GeneratedProgram(code="\n".join(lines), generator="dsl_generator", metadata={"name": name, "operations": [o[0] for o in operations]})

    def generate_ast_transformer(self, name: str, transformations: list[tuple[str, str]]) -> GeneratedProgram:
        """Generate an AST transformer (codemod).

        ``transformations`` is a list of (node_type, description) pairs.
        """
        lines = [
            f'"""Generated AST transformer: {name}"""',
            "import ast",
            "",
            f"class {name.title()}Transformer(ast.NodeTransformer):",
            f'    """{name} — transforms AST nodes."""',
            "",
        ]
        for node_type, desc in transformations:
            method_name = f"visit_{node_type}"
            lines.extend([
                f"    def {method_name}(self, node):",
                f'        """{desc}"""',
                "        self.generic_visit(node)",
                "        return node",
                "",
            ])
        lines.extend([
            f"def apply_{name.lower()}(source: str) -> str:",
            "    tree = ast.parse(source)",
            f"    transformer = {name.title()}Transformer()",
            "    transformer.visit(tree)",
            "    return ast.unparse(tree)",
        ])
        return GeneratedProgram(code="\n".join(lines), generator="ast_transformer_generator", metadata={"name": name})

    def generate_code_generator(self, name: str, template: str, params: list[str]) -> GeneratedProgram:
        """Generate a code generator function."""
        param_str = ", ".join(params)
        lines = [
            f'def generate_{name}({param_str}):',
            f'    """Generate {name} code."""',
            f'    return """{template}""".format({param_str})',
        ]
        return GeneratedProgram(code="\n".join(lines), generator="code_generator_generator", metadata={"name": name})

    def dashboard(self) -> str:
        lines = [
            f"Meta-programmer ({len(self.macros)} macros):",
            "Macros:",
        ]
        for name, desc in self.list_macros():
            lines.append(f"  {name:<20} {desc}")
        return "\n".join(lines)


_metaprogrammer: MetaProgrammer | None = None


def get_metaprogrammer() -> MetaProgrammer:
    global _metaprogrammer
    if _metaprogrammer is None:
        _metaprogrammer = MetaProgrammer()
    return _metaprogrammer
